### ISSUE TITLE
RFC: Dedicated workers

### ISSUE THREAD

**Issue by JakeGinnivan** [JakeGinnivan/gru#1]
We have a scenario where we have a number of subscriptions to different message queues, folder watching, websocket notification etc all running in the master.

This causes the master process to have a lot of contention and from time to time the get arguments from master function times out.

# Proposal

Introduce a new config option `dedicatedWorkers`, this could take an object with type `type DedicatedWorkers = { [workerName: string]: StartFunction }`

These workers would become named workers and gru would manage them like any others (ensuring they are restarted when they crash etc).

## Usage

```
gru({
    dedicatedWorkers: {
         task1: () => startTask1(),
         task2: () => startTask2()
    }
})
```

## Considerations

These workers would support the master args concept

Maybe try to set `process.title` to make it easy to know what processes are what, at least give the option to output pid & the dedicated worker name so if they crash it is easy to know which dedicated worker was restarted,

**Comment by andyjdavis** [comment]
>Maybe try to set process.title to make it easy to know what processes are what, at least give the option to output pid & the dedicated worker name

Would that be sufficient to allow someone to compare memory/cpu usage between dedicated workers?

**Comment by andyjdavis** [comment]
Code to implement dedicated workers has now merged to master.

**Comment by andyjdavis** [comment]
@JakeGinnivan can this issue now be closed? Dedicated workers have existed in Gru for a while. I'm unsure if there is anything left to do.
